### ISSUE TITLE
Fix ImageLink GenerateNewFilename()

### ISSUE THREAD

**Issue by Issung** [Issung/GChan#25]
GenerateNewFilename in ImageLink.cs looks a bit scuffed, it has a switch block assigning to `result`, and then right below a big chunk of if/elses assigning to `result` as well, then some commented out code. Looks like the switch is missing a case too? Update this to the new preffered switch expression pattern matching C# feature, much shorter and easier to read. 
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression

Example of switch expression being used in GChan here: https://github.com/Issung/GChan/blob/8345b0cdb3812625cefd961f4a17edde67631d6a/GChan/Controllers/MainController.cs#L319
and here 
https://github.com/Issung/GChan/blob/8345b0cdb3812625cefd961f4a17edde67631d6a/GChan/Utils.cs#L239

**Comment by orkhanag** [comment]
Hi, I like to work on this. Could you assign it to me, please?

**Comment by Issung** [comment]
There you go, happy to accept contribution :)
