### ISSUE TITLE
Clearing list won't rename folders.

### ISSUE THREAD

**Issue by eva1-x-3** [Issung/GChan#5]
Not sure if it is intentional, however clearing the list with the "clear" button does not rename folders according to the options set.
Maybe that is intentional but i thought it was odd, due to the redundancy of right-clicking and choosing "remove" for each item.
Right-clicking and choosing remove does rename folders according to options.

Great program though, good work!

**Comment by Issung** [comment]
Sorry mate, didn't get a notification about this issue, hopefully that is fixed now, and hopefully so is your issue. 
A fix for your issue has been included in the latest release 4.0.0 https://github.com/Issung/GChan/releases/tag/4.0.0
Please note the paragraph stating this is a breaking release and that you should finish scraping all current threads before upgrading to this release. Please also make sure that all settings in the new version are configured to your desire also. Thanks for your report!
