### ISSUE TITLE
v6.0-beta does not remove dead threads from GChan.

### ISSUE THREAD

**Issue by Boss-Hoss** [Issung/GChan#50]
First, TY for the update. Secondly, it appears dead threads are not removed from GChan and if you have multiple threads it can be hard to determine which ones to remove as there is not a thread ID column (that I can see). Thanks for your continued work

**Comment by Issung** [comment]
Thanks for the report @Boss-Hoss Just verified you are correct. Just made [this commit](https://github.com/Issung/GChan/commit/123d437078bce6a6b5d12c583da564e5a571da31) for the thread to handle the removal and stop processing. Now I need to make the thread remove itself from the UI when this occurs too.

**Comment by Issung** [comment]
New version released https://github.com/Issung/GChan/releases/tag/v6.1-beta
Please test & let me know if it fixes the issue for you. Also added the Id column for you.
Also, please consider donation, if you haven't already.
[Ko-Fi](https://ko-fi.com/issung)
[PayPal](https://www.paypal.com/paypalme/Issung)
[GitHub Sponsor](https://github.com/sponsors/Issung)

**Comment by Boss-Hoss** [comment]
Thank you for the speedy update. I've donated as ourspecialboy. Everything seems to be working as intended. This program is indispensable thank you for maintaining it.

**Comment by Issung** [comment]
I did receive your donation a few days ago, it is appreciated beyond words mate. Thanks for getting back to me on the fix :)
