### ISSUE TITLE
View download progress

### ISSUE THREAD

**Issue by vlad-patras** [Issung/GChan#51]
Feature to view download progress.

The UI shows file count which gives and idea of scraping progress, but there's no indication of what is being downloaded.
We can go to the download folder and compare the file counts foreach thread, but this is cumbersome. It would be great is the UI would show this information.

**Comment by Issung** [comment]
Done in https://github.com/Issung/GChan/commit/3bbaffd372c128a904d14f656e553226ad2b51d4

Thank you!
