### ISSUE TITLE
8kun makes GChan crash and it marks them as gone

### ISSUE THREAD

**Issue by parasiteoflife** [Issung/GChan#9]
I got this in the logs

```
[29/12/2020 00:07:30] - AppDomain_UnhandledException - FormatException - The input string is not in the correct format.
   in System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   in System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   in GChan.Trackers.Thread_8Kun.GetImageLinks()
   in GChan.Trackers.Thread_8Kun.Download()
   in GChan.Trackers.Thread.Download(Object callback)
   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   in System.Threading.ThreadPoolWorkQueue.Dispatch()
```

GChan doesn't download any image, it marks everything as gone.

**Comment by Issung** [comment]
Hi there, in the current release 8kun is currently not supported, though in the current development branch it is now fully supported. I will soon make a new release with this new 8kun functionality and let you know when I do that.

GChan should have let you know it is not supported when you tried to put it in, an oversight on my part, sorry for that.
Thanks for an excellent Issue report too, posting the logs straight away is very useful.

**Comment by 27chan** [comment]
Hey guys,

Make it work in Vichan, it will please many users.

**Comment by Issung** [comment]
Hi there @27chan, what imageboards use vichan? I will investigate them and see if I can work it into the next release

**Comment by 27chan** [comment]
I can't be sure, but many IB's are based on Vichan, including 8kun.
We have a large list at the links below:

https://socialwiki.top/wiki/Imageboards
https://github.com/ccd0/imageboards.json/blob/gh-pages/imageboards.json

**Comment by Issung** [comment]
8kun was always a dump and now it's a dead dump. I'm officially removing support in the next release.
